# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import styles


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 690)
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("background-color:#EEEEEE;")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1041, 671))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.tabWidget.setObjectName("tabWidget")

        self.scripts = QtWidgets.QWidget()
        self.scripts.setObjectName("scripts")

        self.all_scenes = QtWidgets.QLabel(self.scripts)
        self.all_scenes.setGeometry(QtCore.QRect(30, 10, 110, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(16)
        self.all_scenes.setFont(font)
        self.all_scenes.setStyleSheet("color: #222831;")
        self.all_scenes.setObjectName("all_scenes")

        self.list = QtWidgets.QListWidget(self.scripts)
        self.list.setGeometry(QtCore.QRect(20, 50, 401, 571))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.list.setFont(font)
        self.list.setStyleSheet(styles.for_list)
        self.list.setObjectName("list")

        self.add = QtWidgets.QPushButton(self.scripts)
        self.add.setGeometry(QtCore.QRect(310, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add.setFont(font)
        self.add.setMouseTracking(False)
        self.add.setStyleSheet("QPushButton {\n"
                               "    color: white;\n"
                               "    background-color: #FD7013;\n"
                               "    border-radius: 15;\n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "    color: #EEEEEE;\n"
                               "    background-color: #D65F00;\n"
                               "    border-radius: 15;\n"
                               "}")
        self.add.setCheckable(False)
        self.add.setObjectName("add")

        self.frame = QtWidgets.QFrame(self.scripts)
        self.frame.setGeometry(QtCore.QRect(450, 0, 571, 631))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.hide()

        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 360, 511, 251))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.name = QtWidgets.QLineEdit(self.frame)
        self.name.setGeometry(QtCore.QRect(10, 50, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setStyleSheet("border-radius: 15;\n"
                                "background-color: rgb(255, 255, 255);")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")

        self.add_scene = QtWidgets.QLabel(self.frame)
        self.add_scene.setGeometry(QtCore.QRect(20, 10, 240, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(16)
        self.add_scene.setFont(font)
        self.add_scene.setStyleSheet("color: #222831;")
        self.add_scene.setObjectName("add_scene")

        self.add_new_action = QtWidgets.QPushButton(self.frame)
        self.add_new_action.setGeometry(QtCore.QRect(10, 320, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.add_new_action.setFont(font)
        self.add_new_action.setMouseTracking(False)
        self.add_new_action.setStyleSheet("QPushButton {\n"
                                          "    color: white;\n"
                                          "    background-color: #393E46;\n"
                                          "    border-radius: 15;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:pressed {\n"
                                          "    color: #EEEEEE;\n"
                                          "    background-color: #222831;\n"
                                          "    border-radius: 15;\n"
                                          "}")
        self.add_new_action.setCheckable(False)
        self.add_new_action.setObjectName("add_act")

        self.save_before = QtWidgets.QPushButton(self.frame)
        self.save_before.setGeometry(QtCore.QRect(10, 320, 100, 31))
        self.save_before.setVisible(False)
        self.save_before.setText('Добавить')
        self.save_before.setFont(styles.font_ltl_btn)
        self.save_before.setMouseTracking(False)
        self.save_before.setStyleSheet(styles.for_orange_btn)
        self.save_before.setCheckable(False)
        self.save_before.setObjectName("save_act_bf")

        self.act_info = QtWidgets.QLabel(self.frame)
        self.act_info.setGeometry(QtCore.QRect(15, 320, 240, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(14)
        self.act_info.setText('Подробнее о действии')
        self.act_info.setFont(font)
        self.act_info.setStyleSheet("color: #222831;")
        self.act_info.setObjectName("act_info")
        self.act_info.hide()

        self.add_act_res = QtWidgets.QPushButton(self.frame)
        self.add_act_res.setGeometry(QtCore.QRect(10, 320, 100, 31))
        self.add_act_res.setVisible(False)
        self.add_act_res.setText('Добавить')
        self.add_act_res.setFont(styles.font_ltl_btn)
        self.add_act_res.setMouseTracking(False)
        self.add_act_res.setStyleSheet(styles.for_orange_btn)
        self.add_act_res.setCheckable(False)
        self.add_act_res.setObjectName("add_act")

        self.action_cancel = QtWidgets.QPushButton(self.frame)
        self.action_cancel.setGeometry(QtCore.QRect(115, 320, 90, 31))
        self.action_cancel.setFont(styles.font_ltl_btn)
        self.action_cancel.setText('Отменить')
        self.action_cancel.setMouseTracking(False)
        self.action_cancel.setStyleSheet(styles.for_btn)
        self.action_cancel.setCheckable(False)
        self.action_cancel.setObjectName("сancel_add")
        self.action_cancel.setVisible(False)

        self.save_action = QtWidgets.QPushButton(self.frame)
        self.save_action.setGeometry(QtCore.QRect(10, 320, 100, 31))
        self.save_action.setVisible(False)
        self.save_action.setText('Сохранить')
        self.save_action.setFont(styles.font_ltl_btn)
        self.save_action.setMouseTracking(False)
        self.save_action.setStyleSheet(styles.for_orange_btn)
        self.save_action.setCheckable(False)
        self.save_action.setObjectName("save_act")

        self.delete_action = QtWidgets.QPushButton(self.frame)
        self.delete_action.setGeometry(QtCore.QRect(470, 320, 80, 31))
        self.delete_action.setFont(styles.font_ltl_btn)
        self.delete_action.setText('Удалить')
        self.delete_action.setMouseTracking(False)
        self.delete_action.setStyleSheet(styles.for_btn)
        self.delete_action.setCheckable(False)
        self.delete_action.setObjectName("delete_act")
        self.delete_action.setVisible(False)

        self.add_before = QtWidgets.QPushButton(self.frame)
        self.add_before.setGeometry(QtCore.QRect(350, 355, 201, 31))
        self.add_before.setFont(styles.font_ltl_btn)
        self.add_before.setMouseTracking(False)
        self.add_before.setText('Добавить действие перед')
        self.add_before.setVisible(False)
        self.add_before.setStyleSheet(styles.for_btn)
        self.add_before.setCheckable(False)
        self.add_before.setObjectName("add_before")

        self.actions = QtWidgets.QListWidget(self.frame)
        self.actions.setGeometry(QtCore.QRect(10, 90, 511, 221))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.actions.setFont(font)
        self.actions.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                   "border-radius: 20;"
                                   "padding-left: 15px;\n"
                                   "padding-top: 7px;\n"
                                   "padding-right: 15px;")
        self.actions.setObjectName("actions")

        self.save = QtWidgets.QPushButton(self.frame)
        self.save.setGeometry(QtCore.QRect(460, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save.setFont(font)
        self.save.setMouseTracking(False)
        self.save.setStyleSheet("QPushButton {\n"
                                "    color: white;\n"
                                "    background-color: #FD7013;\n"
                                "    border-radius: 15;\n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    color: #EEEEEE;\n"
                                "    background-color: #D65F00;\n"
                                "    border-radius: 15;\n"
                                "}")
        self.save.setCheckable(False)
        self.save.setObjectName("save")

        self.cancel = QtWidgets.QPushButton(self.frame)
        self.cancel.setGeometry(QtCore.QRect(365, 10, 90, 31))
        self.cancel.setText('Отменить')
        self.cancel.setFont(styles.font_ltl_btn)
        self.cancel.setMouseTracking(False)
        self.cancel.setStyleSheet(styles.for_btn)
        self.cancel.setCheckable(False)
        self.cancel.setObjectName("cancel_script")

        self.cancel_edit = QtWidgets.QPushButton(self.frame)
        self.cancel_edit.setGeometry(QtCore.QRect(350, 10, 90, 31))
        self.cancel_edit.setText('Отменить')
        self.cancel_edit.setFont(styles.font_ltl_btn)
        self.cancel_edit.setMouseTracking(False)
        self.cancel_edit.setStyleSheet(styles.for_btn)
        self.cancel_edit.setCheckable(False)
        self.cancel_edit.hide()
        self.cancel_edit.setObjectName("cancel_script")

        self.save_edit = QtWidgets.QPushButton(self.frame)
        self.save_edit.setGeometry(QtCore.QRect(450, 10, 111, 31))
        self.save_edit.setText('Сохранить как')
        self.save_edit.setFont(styles.font_big_btn)
        self.save_edit.setMouseTracking(False)
        self.save_edit.setStyleSheet(styles.for_orange_btn)
        self.save_edit.setCheckable(False)
        self.save_edit.setObjectName("save_edit")
        self.save_edit.setVisible(False)

        self.edit = QtWidgets.QPushButton(self.frame)
        self.edit.setGeometry(QtCore.QRect(460, 10, 101, 31))
        self.edit.setText('Изменить')
        self.edit.setVisible(False)
        self.edit.setFont(styles.font_big_btn)
        self.edit.setMouseTracking(False)
        self.edit.setStyleSheet(styles.for_orange_btn)
        self.edit.setCheckable(False)
        self.edit.setObjectName("edit")

        self.delete = QtWidgets.QPushButton(self.frame)
        self.delete.setGeometry(QtCore.QRect(360, 10, 90, 31))
        self.delete.setText('Удалить')
        self.delete.setFont(styles.font_ltl_btn)
        self.delete.setMouseTracking(False)
        self.delete.setStyleSheet(styles.for_btn)
        self.delete.setCheckable(False)
        self.delete.setVisible(False)
        self.delete.setObjectName("del_script")

        self.code = QtWidgets.QLineEdit(self.frame_2)
        self.code.setGeometry(QtCore.QRect(270, 65, 240, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.code.setFont(font)
        self.code.setStyleSheet("border-radius: 15;\n"
                                "background-color: rgb(255, 255, 255);")
        self.code.setAlignment(QtCore.Qt.AlignCenter)
        self.code.setObjectName("code")
        self.code.hide()

        self.text = QtWidgets.QLineEdit(self.frame_2)
        self.text.setGeometry(QtCore.QRect(0, 130, 511, 121))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.text.setFont(font)
        self.text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                "border-radius: 20;"
                                "padding-left: 15px;\n"
                                "padding-top: 7px;\n"
                                "padding-right: 15px;")
        self.text.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.text.setObjectName("text")
        self.record = QtWidgets.QCheckBox(self.frame_2)
        self.record.setGeometry(QtCore.QRect(5, 5, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.record.setFont(font)
        self.record.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.record.setCheckable(True)
        self.record.setChecked(False)
        self.record.setObjectName("record")

        self.duration = QtWidgets.QLineEdit(self.frame_2)
        self.duration.setGeometry(QtCore.QRect(0, 65, 240, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.duration.setFont(font)
        self.duration.setStyleSheet("border-radius: 15;\n"
                                    "background-color: rgb(255, 255, 255);")
        self.duration.setAlignment(QtCore.Qt.AlignCenter)
        self.duration.setObjectName("duration")
        self.duration.setPlaceholderText('миллисек.')

        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 40, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(280, 40, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_2.hide()

        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 105, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.up_action = QtWidgets.QPushButton(self.frame)
        self.up_action.setGeometry(QtCore.QRect(530, 170, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.up_action.setFont(font)
        self.up_action.setMouseTracking(False)
        self.up_action.setStyleSheet("QPushButton {\n"
                                     "    color: white;\n"
                                     "    background-color: #FD7013;\n"
                                     "    border-radius: 5;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "    color: #EEEEEE;\n"
                                     "    background-color: #D65F00;\n"
                                     "    border-radius: 5;\n"
                                     "}")
        self.up_action.setCheckable(False)
        self.up_action.setObjectName("save_2")
        self.up_action.hide()

        self.down_action = QtWidgets.QPushButton(self.frame)
        self.down_action.setGeometry(QtCore.QRect(530, 210, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.down_action.setFont(font)
        self.down_action.setMouseTracking(False)
        self.down_action.setStyleSheet("QPushButton {\n"
                                       "    color: white;\n"
                                       "    background-color: #FD7013;\n"
                                       "    border-radius: 5;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed {\n"
                                       "    color: #EEEEEE;\n"
                                       "    background-color: #D65F00;\n"
                                       "    border-radius: 5;\n"
                                       "}")
        self.down_action.setCheckable(False)
        self.down_action.setObjectName("save_3")
        self.down_action.hide()

        self.save_as_old = QtWidgets.QPushButton(self.frame)
        self.save_as_old.setGeometry(QtCore.QRect(490, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.save_as_old.setFont(font)
        self.save_as_old.setMouseTracking(False)
        self.save_as_old.setStyleSheet("QPushButton {\n"
                                       "    color: white;\n"
                                       "    background-color: #393E46;\n"
                                       "    border-radius: 15;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed {\n"
                                       "    color: #EEEEEE;\n"
                                       "    background-color: #D65F00;\n"
                                       "    border-radius: 15;\n"
                                       "}")
        self.save_as_old.setCheckable(False)
        self.save_as_old.setObjectName("save_4")
        self.save_as_old.hide()

        self.save_as_new = QtWidgets.QPushButton(self.frame)
        self.save_as_new.setGeometry(QtCore.QRect(410, 50, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.save_as_new.setFont(font)
        self.save_as_new.setMouseTracking(False)
        self.save_as_new.setStyleSheet("QPushButton {\n"
                                       "    color: white;\n"
                                       "    background-color: #393E46;\n"
                                       "    border-radius: 15;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed {\n"
                                       "    color: #EEEEEE;\n"
                                       "    background-color: #D65F00;\n"
                                       "    border-radius: 15;\n"
                                       "}")
        self.save_as_new.setCheckable(False)
        self.save_as_new.setObjectName("save_5")
        self.save_as_new.hide()

        self.tabWidget.addTab(self.scripts, "")
        self.rec = QtWidgets.QWidget()
        self.rec.setObjectName("rec")
        self.tabWidget.addTab(self.rec, "")

        self.rec.setObjectName("rec")
        self.stackedWidget = QtWidgets.QStackedWidget(self.rec)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1031, 641))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.list_2 = QtWidgets.QListWidget(self.page)
        self.list_2.setGeometry(QtCore.QRect(215, 50, 600, 581))
        self.list_2.setStyleSheet(styles.for_list)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(12)
        self.list_2.setFont(font)
        self.list_2.setObjectName("list_2")

        self.choose_script = QtWidgets.QLabel(self.page)
        self.choose_script.setGeometry(QtCore.QRect(220, 10, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(18)
        self.choose_script.setFont(font)
        self.choose_script.setStyleSheet("color: #222831;")
        self.choose_script.setObjectName("choose_script")
        self.select = QtWidgets.QPushButton(self.page)
        self.select.setGeometry(QtCore.QRect(820, 90, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.select.setFont(font)
        self.select.setMouseTracking(False)
        self.select.setStyleSheet("QPushButton {\n"
                                  "    color: white;\n"
                                  "    background-color: #FD7013;\n"
                                  "    border-radius: 10;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    color: #EEEEEE;\n"
                                  "    background-color: #D65F00;\n"
                                  "    border-radius: 10;\n"
                                  "}")
        self.select.setCheckable(False)
        self.select.setObjectName("select")
        self.select.hide()

        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.listView = QtWidgets.QListWidget(self.page_2)
        self.listView.setGeometry(QtCore.QRect(20, 50, 801, 371))
        self.listView.setStyleSheet(styles.for_actions)
        self.listView.setFont(styles.font_list)
        self.listView.setObjectName("listView")

        self.name_of_data = QtWidgets.QLineEdit(self.page_2)
        self.name_of_data.setGeometry(QtCore.QRect(30, 470, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(11)
        self.name_of_data.setFont(font)
        self.name_of_data.setStyleSheet("border-radius: 20;\n"
                                        "background-color: rgb(255, 255, 255);")
        self.name_of_data.setAlignment(QtCore.Qt.AlignCenter)
        self.name_of_data.setObjectName("name")
        self.name_of_data.setPlaceholderText('При отсутствии ввода файлу будет присвоено имя сценария')

        self.choose_script_3 = QtWidgets.QLabel(self.page_2)
        self.choose_script_3.setGeometry(QtCore.QRect(30, 430, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(16)
        self.choose_script_3.setFont(font)
        self.choose_script_3.setStyleSheet("color: #222831;")
        self.choose_script_3.setObjectName("choose_script_2")
        self.choose_script_3.setText('Имя выходного файла')

        self.start = QtWidgets.QPushButton(self.page_2)
        self.start.setGeometry(QtCore.QRect(840, 370, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setMouseTracking(False)
        self.start.setStyleSheet("QPushButton {\n"
                                 "    color: white;\n"
                                 "    background-color: #FD7013;\n"
                                 "    border-radius: 20;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    color: #EEEEEE;\n"
                                 "    background-color: #D65F00;\n"
                                 "    border-radius: 20;\n"
                                 "}")
        self.start.setCheckable(False)
        self.start.setObjectName("start")

        self.choose_script_2 = QtWidgets.QLabel(self.page_2)
        self.choose_script_2.setGeometry(QtCore.QRect(30, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(16)
        self.choose_script_2.setFont(font)
        self.choose_script_2.setStyleSheet("color: #222831;")
        self.choose_script_2.setObjectName("choose_script_2")

        self.change_scene = QtWidgets.QPushButton(self.page_2)
        self.change_scene.setGeometry(QtCore.QRect(840, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.change_scene.setFont(font)
        self.change_scene.setMouseTracking(False)
        self.change_scene.setStyleSheet("QPushButton {\n"
                                        "    color: white;\n"
                                        "    background-color: rgb(57, 62, 70);\n"
                                        "    border-radius: 15;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    color: #EEEEEE;\n"
                                        "    background-color: #D65F00;\n"
                                        "    border-radius: 15;\n"
                                        "}")
        self.change_scene.setCheckable(False)
        self.change_scene.setObjectName("change_scene")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.tabWidget.addTab(self.rec, "")

        self.cancel_select = QtWidgets.QPushButton(self.page_2)
        self.cancel_select.setGeometry(QtCore.QRect(240, 10, 90, 31))
        self.cancel_select.setText('Отмена')
        self.cancel_select.setFont(styles.font_ltl_btn)
        self.cancel_select.setMouseTracking(False)
        self.cancel_select.setStyleSheet(styles.for_btn)
        self.cancel_select.setCheckable(False)
        self.cancel_select.setObjectName("cancel_script")

        self.bck_for_record = QtWidgets.QLabel(self.page_3)
        self.bck_for_record.setGeometry(QtCore.QRect(10, 20, 1001, 601))
        self.bck_for_record.setFont(styles.font_rec)
        self.bck_for_record.setAlignment(QtCore.Qt.AlignCenter)
        self.bck_for_record.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                          "color: rgb(255, 255, 255);")

        self.cancel_record = QtWidgets.QPushButton(self.page_3)
        self.cancel_record.setGeometry(QtCore.QRect(910, 30, 90, 31))
        self.cancel_record.setText('Отмена')
        self.cancel_record.setFont(styles.font_ltl_btn)
        self.cancel_record.setMouseTracking(False)
        self.cancel_record.setStyleSheet(styles.for_orange_btn)
        self.cancel_record.setCheckable(False)
        self.cancel_record.setObjectName("cancel_record")
        self.cancel_record.hide()

        self.close_record = QtWidgets.QPushButton(self.page_3)
        self.close_record.setGeometry(QtCore.QRect(435, 390, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.close_record.setFont(font)
        self.close_record.setMouseTracking(False)
        self.close_record.setStyleSheet("QPushButton {\n"
                                        "    color: white;\n"
                                        "    background-color: #FD7013;\n"
                                        "    border-radius: 20;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    color: #EEEEEE;\n"
                                        "    background-color: #D65F00;\n"
                                        "    border-radius: 20;\n"
                                        "}")
        self.close_record.setCheckable(False)
        self.close_record.setObjectName("cls")
        self.close_record.hide()
        self.close_record.setText('Закрыть')

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1035, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.all_scenes.setText(_translate("MainWindow", "Cценарии"))
        self.add.setText(_translate("MainWindow", "Добавить"))
        self.add_scene.setText(_translate("MainWindow", "Добавление сценария"))
        self.add_new_action.setText(_translate("MainWindow", "Добавить действие"))
        self.save.setText(_translate("MainWindow", "Сохранить"))
        self.record.setText(_translate("MainWindow", "Записывать данные на шаге"))
        self.label.setText(_translate("MainWindow", "Длительность:"))
        self.label_2.setText(_translate("MainWindow", "Метка класса:"))
        self.label_3.setText(_translate("MainWindow", "Текст команды:"))
        self.up_action.setText(_translate("MainWindow", "Up"))
        self.down_action.setText(_translate("MainWindow", "Dwn"))
        self.save_as_old.setText(_translate("MainWindow", "Заменить"))
        self.save_as_new.setText(_translate("MainWindow", "Новый"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.scripts), _translate("MainWindow", "Сценарии"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rec), _translate("MainWindow", "Запись данных"))
        self.choose_script.setText(_translate("MainWindow", "Выберите сценарий, по которому будет выполняться запись"))
        self.select.setText(_translate("MainWindow", "Подтвердить"))
        self.start.setText(_translate("MainWindow", "Начать запись"))
        self.choose_script_2.setText(_translate("MainWindow", "Выбранный сценарий"))
        self.change_scene.setText(_translate("MainWindow", "Редактировть сценарий"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
